export const employees = [
  {
    ID: 0,
    FirstName: "Fabiano",
    LastName: "Zanqueta",
    Prefix: "Sr.",
    Position: "Desenvolvedor",
    BirthDate: "1991/06/25",
    Notes: "Pessoa com força de vontade",
    Address: "351 S Hill St.",
  },
  {
    ID: 1,
    FirstName: "Denis",
    LastName: "Rabello",
    Prefix: "Sr.",
    Position: "Desenvolvedor",
    BirthDate: "1990/11/16",
    Notes: "Um ótimo desenvolvedor",
    Address: "807 W Paseo Del Mar",
  },
  {
    ID: 2,
    FirstName: "Isabelle",
    LastName: "Barragão",
    Prefix: "Sra.",
    Position: "Estudante",
    BirthDate: "2009/02/18",
    Notes: "Uma estudante incrivel",
    Address: "4 Westmoreland Pl.",
  },
];
